language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - 2.2.2
  - jruby-19mode
  - rbx-19mode
script: 'bundle exec rspec'
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
